"""Research memory writer entrypoints used by researcher learning.

The physical implementations still live in phase4_review during the migration,
but researcher learning imports them through this function-named module so the
active boundary is clear: reviewer validates facts, researcher writes learning.
"""

from __future__ import annotations

from tools.agent_tools.research import phase4_review as _phase4


ensure_research_learning_schema = _phase4._ensure_research_learning_schema
write_signal_context_history = _phase4._write_signal_context_history
write_strategy_memory_history = _phase4._write_strategy_memory_history
write_template_and_analyst_learning = _phase4._write_template_and_analyst_learning
write_trade_episode_memory = _phase4._write_trade_episode_memory
write_opportunity_ranking_learning_events = _phase4._write_opportunity_ranking_learning_events
write_no_trade_opportunity_memory = _phase4._write_no_trade_opportunity_memory
backfill_no_trade_opportunity_counterfactual_results = _phase4._backfill_no_trade_opportunity_counterfactual_results
backfill_neutral_forward_counterfactual_tracking = _phase4._backfill_neutral_forward_counterfactual_tracking
write_missed_alpha_accountability_state = _phase4._write_missed_alpha_accountability_state
write_research_position_feedback = _phase4._write_research_position_feedback
write_adaptive_policy_state = _phase4._write_adaptive_policy_state
write_tail_loss_sentinel_state = _phase4._write_tail_loss_sentinel_state
write_alpha_promotion_state = _phase4._write_alpha_promotion_state
write_contextual_rule_calibration_state = _phase4._write_contextual_rule_calibration_state
write_loss_template_observation_research = _phase4._write_loss_template_observation_research
write_fast_loss_sentinel_state = _phase4._write_fast_loss_sentinel_state
write_learned_vs_unlearned_policy_state = _phase4._write_learned_vs_unlearned_policy_state
write_learning_mechanism_policy_state = _phase4._write_learning_mechanism_policy_state
write_provisional_policy_state = _phase4._write_provisional_policy_state
write_config_overlay = _phase4._write_config_overlay
write_neutral_accountability_state = _phase4._write_neutral_accountability_state
write_neutral_accountability_digests = _phase4._write_neutral_accountability_digests
write_capital_deployment_state = _phase4._write_capital_deployment_state
write_validated_causal_policy_rules = _phase4._write_validated_causal_policy_rules
export_template_prior = _phase4._export_template_prior
